import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,useNavigate,Routes,Route,Link} from "react-router-dom";
import {Menu,X,ArrowRight,MapPin,Phone,Instagram,MessageCircle,Clock3,ChevronRight,ShieldCheck,CalendarDays,Save,Trash2,Upload,Settings,LogOut} from "lucide-react";
import "./index.css";
import {supabase} from "./lib/supabase";

const seedPlans=[["1 Month","₹2,500"],["3 Months","₹6,000"],["6 Months","₹9,000"],["Yearly","₹15,000"],["Per Day","₹300"]];
const facilities=["Strength","Cardio","CrossFit","Yoga","Aerobics","Zumba","Steam"];
const contact={phone:"+91 96606 19130",alt:"+91 80056 11906",whatsapp:"919660619130",address:"5, Gulab Nagar C, Near RTO Office, Paota, Jodhpur, Rajasthan",instagram:"https://www.instagram.com/powerliftfitnessgym?stkn=ZDgyMGxhZHk0Y3ow",maps:"https://maps.app.goo.gl/LSRNVPmsVhtAbqU37"};

function useData(){
 const [plans,setPlans]=useState(seedPlans.map(([name,price],i)=>({id:i,name,price})));
 const [settings,setSettings]=useState({name:"POWER LIFT FITNESS",about:"Train with purpose. Build strength, discipline and confidence in a premium fitness environment.",hours:"Timings set by owner",hero:""});
 const [gallery,setGallery]=useState([]);
 useEffect(()=>{(async()=>{if(!supabase)return; const p=await supabase.from("membership_plans").select("*").eq("is_active",true).order("sort_order"); if(!p.error&&p.data?.length)setPlans(p.data); const s=await supabase.from("gym_settings").select("*").limit(1).maybeSingle(); if(!s.error&&s.data)setSettings(s.data); const g=await supabase.from("gallery").select("*").eq("is_published",true).order("created_at",{ascending:false}); if(!g.error)setGallery(g.data||[])})()},[]);
 return {plans,settings,gallery};
}
function Header({settings}){const [open,setOpen]=useState(false);return <header className="fixed top-0 z-50 w-full border-b border-white/10 bg-black/75 backdrop-blur-xl"><div className="container-x flex h-[76px] items-center justify-between"><Link to="/" className="flex items-center gap-3">{settings?.logo_url?<img src={settings.logo_url} className="h-11 w-auto object-contain"/>:<><div className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 bg-white/5 font-black"><span className="orange">P</span>L</div><div className="leading-none"><b className="text-sm tracking-[.22em]">POWER LIFT</b><small className="mt-1 block text-[9px] tracking-[.35em] text-white/50">FITNESS</small></div></>}</Link><nav className="hidden items-center gap-7 text-sm text-white/70 md:flex">{["About","Facilities","Memberships","Gallery","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} className="hover:text-white">{x}</a>)}<Link to="/admin/login" className="btn btn-ghost !px-4 !py-2 text-xs text-white">Admin Login</Link></nav><button className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-white/10 bg-black px-6 py-5 md:hidden">{["About","Facilities","Memberships","Gallery","Contact"].map(x=><a onClick={()=>setOpen(false)} className="block border-b border-white/5 py-4 text-white/75" href={"#"+x.toLowerCase()} key={x}>{x}</a>)}<Link onClick={()=>setOpen(false)} to="/admin/login" className="mt-4 flex justify-center rounded-xl bg-white/10 py-3 font-bold">Admin Login</Link></div>}</header>}
function WhatsApp(){return <a aria-label="WhatsApp" href={"https://wa.me/"+contact.whatsapp+"?text="+encodeURIComponent("Hi Power Lift Fitness, I would like to enquire about the gym.")} target="_blank" rel="noreferrer" className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-[#25D366] text-white shadow-2xl transition hover:scale-105"><MessageCircle fill="currentColor"/></a>}
function Home(){const {plans,settings,gallery}=useData();return <div><Header settings={settings}/><main>
<section className="relative grid min-h-[720px] place-items-center overflow-hidden pt-24"><div className="absolute inset-0 grid-noise opacity-40"/><div className="absolute -right-40 top-40 h-96 w-96 rounded-full bg-orange-600/10 blur-3xl"/><div className="container-x relative grid gap-10 md:grid-cols-[1.1fr_.9fr] md:items-center"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-orange-500/25 bg-orange-500/5 px-4 py-2 text-xs font-bold tracking-[.18em] text-orange-400"><ShieldCheck size={14}/> TRAIN HARD. LIVE STRONG.</div><h1 className="max-w-4xl text-5xl font-black leading-[.94] tracking-[-.05em] sm:text-7xl md:text-8xl">{(settings.hero_heading||"BUILD THE STRONGER VERSION.").split(" ").map((w,i)=><React.Fragment key={i}>{w}{i<2?" ":null}</React.Fragment>)}</h1><p className="mt-7 max-w-xl text-base leading-7 text-white/55">{settings.about}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#booking" className="btn btn-orange">Book a Visit <ArrowRight size={17}/></a><a href={settings.maps_url||contact.maps} target="_blank" rel="noreferrer" className="btn btn-ghost"><MapPin size={17}/> Get Directions</a></div></div><div className="relative hidden aspect-[4/5] overflow-hidden rounded-[32px] border border-white/10 bg-gradient-to-br from-white/10 to-transparent md:block"><div className="absolute inset-0 grid place-items-center">{settings.hero_image_url?<img src={settings.hero_image_url} className="h-full w-full object-cover opacity-70"/>:<div className="text-center"><div className="text-9xl font-black italic text-white/5">PL</div><div className="mt-4 text-xs tracking-[.4em] text-orange-400">POWER LIFT FITNESS</div></div>}</div></div></div></section>
<section id="about" className="section border-y border-white/5"><div className="container-x grid gap-10 md:grid-cols-2"><div><p className="orange text-xs font-bold tracking-[.3em]">THE CLUB</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">TRAIN WITH<br/>INTENT.</h2></div><div className="self-end text-white/55 leading-8"><p>Power Lift Fitness is built around strength, movement and consistency. Whether you are starting out or chasing your next personal best, the space is designed to keep your training focused.</p><div className="mt-8 grid grid-cols-2 gap-3"><div className="glass rounded-2xl p-5"><b className="text-2xl">7+</b><p className="mt-1 text-xs text-white/45">TRAINING OPTIONS</p></div><div className="glass rounded-2xl p-5"><b className="text-2xl">₹300</b><p className="mt-1 text-xs text-white/45">DAY PASS</p></div></div></div></div></section>
<section id="facilities" className="section"><div className="container-x"><p className="orange text-xs font-bold tracking-[.3em]">WHAT WE OFFER</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="text-4xl font-black sm:text-6xl">EVERY SESSION.<br/>MORE POWER.</h2><p className="max-w-sm text-sm leading-6 text-white/45">A focused mix of strength, conditioning, movement and recovery.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{facilities.map((f,i)=><div className="glass group rounded-2xl p-5 transition hover:-translate-y-1 hover:border-orange-500/30" key={f}><span className="text-xs text-white/25">0{i+1}</span><h3 className="mt-12 text-lg font-bold">{f}</h3><ChevronRight className="mt-5 text-orange-500 opacity-0 transition group-hover:opacity-100" size={17}/></div>)}</div></div></section>
<section id="memberships" className="section border-y border-white/5 bg-white/[.015]"><div className="container-x"><div className="text-center"><p className="orange text-xs font-bold tracking-[.3em]">MEMBERSHIPS</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">CHOOSE YOUR<br/>COMMITMENT.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{plans.map((p,i)=><div className={"glass rounded-3xl p-6 "+(p.name==="Yearly"?"border-orange-500/50 shadow-glow":"")} key={p.id}><span className="text-xs font-bold text-white/35">0{i+1}</span><h3 className="mt-8 font-bold">{p.name}</h3><div className="mt-3 text-3xl font-black">{p.price}</div><a href="#booking" className="mt-8 flex items-center gap-2 text-xs font-bold text-orange-400">BOOK NOW <ArrowRight size={14}/></a></div>)}</div><p className="mt-8 text-center text-xs text-white/30">Steam Bath — ₹250</p></div></section>
<section id="gallery" className="section"><div className="container-x"><div className="flex items-end justify-between"><div><p className="orange text-xs font-bold tracking-[.3em]">THE SPACE</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">GALLERY</h2></div></div>{gallery.length?<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{gallery.map(g=><div key={g.id} className="overflow-hidden rounded-3xl border border-white/10 bg-white/5">{g.media_type==="video"?<video controls src={g.public_url} className="aspect-[4/3] w-full object-cover"/>:<img src={g.public_url||g.url} className="aspect-[4/3] w-full object-cover" />}</div>)}</div>:<div className="mt-10 rounded-3xl border border-dashed border-white/10 p-14 text-center text-white/35">Gym gallery is being prepared. Photos and videos will appear here.</div>}</div></section>
<section id="booking" className="section border-y border-white/5"><div className="container-x grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="orange text-xs font-bold tracking-[.3em]">START HERE</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">BOOK A<br/><span className="orange">VISIT.</span></h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/45">Send your details and the team will get in touch to confirm your visit or enquiry.</p></div><BookingForm/></div></section>
<section id="contact" className="section"><div className="container-x"><p className="orange text-xs font-bold tracking-[.3em]">FIND US</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">COME TRAIN.</h2><div className="mt-10 grid gap-3 md:grid-cols-2"><a href={"tel:"+(settings.phone||contact.phone).replace(/\s/g,"")} className="glass rounded-2xl p-6"><Phone className="orange"/><p className="mt-6 text-xs text-white/40">CALL</p><b className="mt-1 block">{settings.phone||contact.phone}</b></a><a href={settings.instagram_url||contact.instagram} target="_blank" rel="noreferrer" className="glass rounded-2xl p-6"><Instagram className="orange"/><p className="mt-6 text-xs text-white/40">INSTAGRAM</p><b className="mt-1 block">@powerliftfitnessgym</b></a><a href={settings.maps_url||contact.maps} target="_blank" rel="noreferrer" className="glass rounded-2xl p-6 md:col-span-2"><MapPin className="orange"/><p className="mt-6 text-xs text-white/40">LOCATION</p><b className="mt-1 block">{settings.address||contact.address}</b></a><div className="glass rounded-2xl p-6 md:col-span-2"><Clock3 className="orange"/><p className="mt-6 text-xs text-white/40">TIMINGS</p><b className="mt-1 block">{settings.timings||"Timings set by owner"}</b></div></div></div></section>
</main><footer className="border-t border-white/10 py-8"><div className="container-x flex flex-col gap-4 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} POWER LIFT FITNESS</span><Link to="/admin/login" className="text-white/55 hover:text-white">Admin Login</Link></div></footer><WhatsApp/></div>}
function BookingForm(){const [form,setForm]=useState({name:"",phone:"",date:"",time:"",type:"Gym Visit",message:""});const [done,setDone]=useState(false);async function submit(e){e.preventDefault();if(supabase){const {error}=await supabase.from("enquiries").insert([{...form,status:"New"}]);if(error){alert(error.message);return}}else{console.log("Demo enquiry",form)}setDone(true)}if(done)return <div className="glass rounded-3xl p-10"><CalendarDays className="orange" size={34}/><h3 className="mt-6 text-2xl font-black">REQUEST RECEIVED.</h3><p className="mt-3 text-sm leading-6 text-white/45">Thanks! The Power Lift Fitness team will contact you to confirm.</p></div>;return <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">{[["name","Your name"],["phone","Phone number"],["date","Preferred date"],["time","Preferred time"]].map(([k,p])=><input required key={k} type={k==="date"?"date":k==="time"?"time":"text"} placeholder={p} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm outline-none placeholder:text-white/25 focus:border-orange-500/50"/>) }<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="rounded-2xl border border-white/10 bg-[#111] px-5 py-4 text-sm sm:col-span-2"><option>Gym Visit</option><option>Membership Enquiry</option><option>Day Pass</option><option>General Enquiry</option></select><textarea rows="5" placeholder="Message (optional)" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm outline-none placeholder:text-white/25 focus:border-orange-500/50 sm:col-span-2"/><button className="btn btn-orange w-full sm:col-span-2">Send Enquiry <ArrowRight size={17}/></button></form>}
function AdminLogin(){const nav=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [err,setErr]=useState("");async function login(e){e.preventDefault();if(!supabase){setErr("Add Supabase environment variables first.");return}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message);else nav("/admin")}return <div className="grid min-h-screen place-items-center bg-[#050505] p-5"><div className="w-full max-w-md"><Link to="/" className="mb-8 inline-flex text-sm text-white/45 hover:text-white">← Back to website</Link><div className="glass rounded-3xl p-8 sm:p-10"><div className="orange text-xs font-bold tracking-[.3em]">POWER LIFT FITNESS</div><h1 className="mt-3 text-4xl font-black">ADMIN LOGIN</h1><p className="mt-3 text-sm text-white/40">Manage gym details, plans, gallery and enquiries.</p><form onSubmit={login} className="mt-8 space-y-3"><input required type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-5 py-4 outline-none"/><input required type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-5 py-4 outline-none"/>{err&&<p className="rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{err}</p>}<button className="btn btn-orange w-full">Sign In <ArrowRight size={17}/></button></form></div></div></div>}
function Admin(){const [session,setSession]=useState(null);const [tab,setTab]=useState("overview");const nav=useNavigate();useEffect(()=>{if(!supabase){return}supabase.auth.getSession().then(({data})=>{if(!data.session)nav("/admin/login");else setSession(data.session)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);if(!supabase)return <div className="p-10">Configure Supabase first.</div>;if(!session)return <div className="min-h-screen grid place-items-center">Checking session…</div>;return <div className="min-h-screen bg-[#070707]"><aside className="fixed hidden h-full w-64 border-r border-white/10 bg-black p-6 md:block"><div className="text-sm font-black tracking-[.2em]">POWER <span className="orange">LIFT</span></div><div className="mt-10 space-y-2">{["overview","gym","plans","gallery","enquiries","settings"].map(x=><button onClick={()=>setTab(x)} className={"w-full rounded-xl px-4 py-3 text-left text-sm "+(tab===x?"bg-orange-500 text-white":"text-white/45 hover:bg-white/5")} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><button onClick={async()=>{await supabase.auth.signOut();nav("/admin/login")}} className="absolute bottom-8 left-6 text-sm text-white/40">Logout</button></aside><main className="p-5 md:ml-64 md:p-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="orange text-xs font-bold tracking-[.3em]">CONTROL ROOM</p><h1 className="mt-2 text-4xl font-black">{tab.toUpperCase()}</h1></div><Link to="/" className="btn btn-ghost text-xs">View Site</Link></div><div className="mt-10">{tab==="overview"?<div className="grid gap-4 sm:grid-cols-3"><div className="glass rounded-3xl p-6"><p className="text-xs text-white/35">CONTENT</p><b className="mt-3 block text-3xl">Manage</b><p className="mt-2 text-sm text-white/40">Gym information & branding</p></div><div className="glass rounded-3xl p-6"><p className="text-xs text-white/35">MEDIA</p><b className="mt-3 block text-3xl">Gallery</b><p className="mt-2 text-sm text-white/40">Photos & videos</p></div><div className="glass rounded-3xl p-6"><p className="text-xs text-white/35">LEADS</p><b className="mt-3 block text-3xl">Enquiries</b><p className="mt-2 text-sm text-white/40">Booking requests</p></div></div>:tab==="gym"?<GymEditor/>:tab==="plans"?<PlansManager/>:tab==="gallery"?<GalleryManager/>:tab==="enquiries"?<EnquiriesManager/>:<SettingsPage/>}</div></div></main></div>}
function GymEditor(){
 const [d,setD]=useState({name:"",about:"",phone:"",whatsapp:"",instagram_url:"",maps_url:"",address:"",timings:"",hero_image_url:"",logo_url:"/power-lift-logo-reference.jpg"}); const [msg,setMsg]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const {data}=await supabase.from("gym_settings").select("*").limit(1).maybeSingle();if(data)setD({...d,...data})})()},[]);
 async function upload(file,key){if(!file)return;const ext=file.name.split(".").pop();const path=`${key}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("branding").upload(path,file);if(error)return alert(error.message);const {data:u}=supabase.storage.from("branding").getPublicUrl(path);setD(x=>({...x,[key+"_url"]:u.publicUrl}))}
 async function save(e){e.preventDefault();setSaving(true);const {error}=await supabase.from("gym_settings").update({...d,updated_at:new Date().toISOString()}).eq("id",d.id);setMsg(error?error.message:"Saved successfully.");setSaving(false)}
 return <form onSubmit={save} className="glass rounded-3xl p-6"><div className="grid gap-3 sm:grid-cols-2">{[["name","Gym name"],["phone","Primary phone"],["alt_phone","Second phone"],["whatsapp","WhatsApp"],["instagram_url","Instagram URL"],["maps_url","Google Maps URL"],["address","Address"],["timings","Timings"],["hero_image_url","Hero image URL"],["logo_url","Logo URL"]].map(([k,l])=><label className="text-xs text-white/45" key={k}>{l}<input className="input mt-2" value={d[k]||""} onChange={e=>setD({...d,[k]:e.target.value})}/></label>)}<label className="text-xs text-white/45 sm:col-span-2">About<textarea className="input mt-2" rows="4" value={d.about||""} onChange={e=>setD({...d,about:e.target.value})}/></label><div className="glass rounded-2xl p-4 text-xs text-white/45">Upload logo<input className="mt-3 block w-full" type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],"logo")}/></div><div className="glass rounded-2xl p-4 text-xs text-white/45">Upload hero image<input className="mt-3 block w-full" type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],"hero_image")}/></div></div>{msg&&<p className="mt-4 text-sm text-white/55">{msg}</p>}<button disabled={saving} className="btn btn-orange mt-5"><Save size={16}/>{saving?"Saving…":"Save Gym Details"}</button></form>
}
function PlansManager(){
 const blank={name:"",price:"",description:"",is_active:true,is_featured:false,sort_order:0};const [rows,setRows]=useState([]),[f,setF]=useState(blank),[edit,setEdit]=useState(null);
 const load=async()=>{const {data}=await supabase.from("membership_plans").select("*").order("sort_order");setRows(data||[])};useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();const payload={...f,price:Number(f.price),sort_order:Number(f.sort_order)||0};const q=edit?supabase.from("membership_plans").update(payload).eq("id",edit):supabase.from("membership_plans").insert([payload]);const {error}=await q;if(error)alert(error.message);else{setF(blank);setEdit(null);load()}}
 async function del(id){if(confirm("Delete this plan?")){const {error}=await supabase.from("membership_plans").delete().eq("id",id);if(error)alert(error.message);else load()}}
 return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={save} className="glass rounded-3xl p-6"><h2 className="font-black">{edit?"EDIT PLAN":"ADD PLAN"}</h2><div className="mt-5 space-y-3"><input className="input" required placeholder="Plan name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input className="input" required type="number" placeholder="Price" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><input className="input" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input className="input" type="number" placeholder="Sort order" value={f.sort_order} onChange={e=>setF({...f,sort_order:e.target.value})}/><label className="block text-sm text-white/55"><input type="checkbox" checked={f.is_active} onChange={e=>setF({...f,is_active:e.target.checked})}/> Active</label><label className="block text-sm text-white/55"><input type="checkbox" checked={f.is_featured} onChange={e=>setF({...f,is_featured:e.target.checked})}/> Featured</label></div><button className="btn btn-orange mt-5 w-full"><Save size={16}/>{edit?"Update":"Add"}</button></form><div className="space-y-3">{rows.map(r=><div className="glass flex items-center gap-3 rounded-2xl p-4" key={r.id}><div className="flex-1"><b>{r.name}</b><p className="text-sm text-white/40">₹{Number(r.price).toLocaleString("en-IN")} · {r.description||"No description"}</p></div><button onClick={()=>{setEdit(r.id);setF({...r})}} className="rounded-xl bg-white/5 px-3 py-2 text-xs">Edit</button><button onClick={()=>del(r.id)} className="rounded-xl bg-red-500/10 p-3 text-red-300"><Trash2 size={16}/></button></div>)}</div></div>
}
function GalleryManager(){
 const [rows,setRows]=useState([]),[file,setFile]=useState(null),[title,setTitle]=useState(""),[caption,setCaption]=useState(""),[type,setType]=useState("image");const load=async()=>{const {data}=await supabase.from("gallery").select("*").order("created_at",{ascending:false});setRows(data||[])};useEffect(()=>{load()},[]);
 async function add(e){e.preventDefault();if(!file)return;const ext=file.name.split(".").pop();const path=`${crypto.randomUUID()}.${ext}`;const {error:u}=await supabase.storage.from("gallery").upload(path,file);if(u)return alert(u.message);const {data:pub}=supabase.storage.from("gallery").getPublicUrl(path);const {error}=await supabase.from("gallery").insert([{title,caption,media_type:type,storage_path:path,public_url:pub.publicUrl,is_published:true}]);if(error)alert(error.message);else{setTitle("");setCaption("");setFile(null);e.target.reset();load()}}
 async function edit(r){const t=prompt("Title",r.title||"");if(t===null)return;const c=prompt("Caption",r.caption||"");if(c===null)return;await supabase.from("gallery").update({title:t,caption:c}).eq("id",r.id);load()}
 async function del(r){if(!confirm("Delete this item?"))return;await supabase.from("gallery").delete().eq("id",r.id);if(r.storage_path)await supabase.storage.from("gallery").remove([r.storage_path]);load()}
 return <div><form onSubmit={add} className="glass rounded-3xl p-6"><div className="grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><select className="input bg-[#111]" value={type} onChange={e=>setType(e.target.value)}><option value="image">Photo</option><option value="video">Video</option></select><input className="input sm:col-span-2" placeholder="Caption" value={caption} onChange={e=>setCaption(e.target.value)}/><input required className="block w-full text-sm text-white/45 sm:col-span-2" type="file" accept="image/*,video/*" onChange={e=>{const f=e.target.files?.[0];setFile(f);if(f)setType(f.type.startsWith("video/")?"video":"image")}}/></div><button className="btn btn-orange mt-5"><Upload size={16}/>Upload</button></form><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><div className="overflow-hidden rounded-3xl border border-white/10" key={r.id}>{r.media_type==="video"?<video controls src={r.public_url} className="aspect-[4/3] w-full object-cover"/>:<img src={r.public_url} className="aspect-[4/3] w-full object-cover"/>}<div className="flex gap-2 p-3"><button onClick={()=>edit(r)} className="rounded-xl bg-white/5 px-3 py-2 text-xs">Edit</button><button onClick={()=>del(r)} className="rounded-xl bg-red-500/10 p-2 text-red-300"><Trash2 size={16}/></button></div></div>)}</div></div>
}
function EnquiriesManager(){const [rows,setRows]=useState([]);const load=async()=>{const {data}=await supabase.from("enquiries").select("*").order("created_at",{ascending:false});setRows(data||[])};useEffect(()=>{load()},[]);async function st(id,v){await supabase.from("enquiries").update({status:v}).eq("id",id);load()}async function del(id){if(confirm("Delete enquiry?")){await supabase.from("enquiries").delete().eq("id",id);load()}}return <div className="space-y-3">{rows.map(r=><div className="glass rounded-3xl p-5" key={r.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><b className="text-lg">{r.name}</b><p className="mt-1 text-sm text-white/45">{r.phone} · {r.date||"No date"} {r.time||""} · {r.type||"Enquiry"}</p>{r.message&&<p className="mt-3 text-sm text-white/55">{r.message}</p>}</div><select className="rounded-xl border border-white/10 bg-[#111] px-3 py-2 text-xs" value={r.status} onChange={e=>st(r.id,e.target.value)}><option>New</option><option>Contacted</option><option>Completed</option></select><button onClick={()=>del(r.id)} className="rounded-xl bg-red-500/10 p-3 text-red-300"><Trash2 size={16}/></button></div></div>)}{!rows.length&&<div className="glass rounded-3xl p-10 text-center text-white/35">No enquiries yet.</div>}</div>}
function SettingsPage(){const [p,setP]=useState(""),[c,setC]=useState(""),[msg,setMsg]=useState("");async function save(e){e.preventDefault();if(p.length<6)return setMsg("Use at least 6 characters.");if(p!==c)return setMsg("Passwords do not match.");const {error}=await supabase.auth.updateUser({password:p});setMsg(error?error.message:"Password changed successfully.");if(!error){setP("");setC("")}}return <div className="glass max-w-xl rounded-3xl p-6"><div className="flex items-center gap-3"><Settings className="orange"/><h2 className="font-black">ADMIN SETTINGS</h2></div><form onSubmit={save} className="mt-6 space-y-3"><input className="input" type="password" minLength="6" required placeholder="New password" value={p} onChange={e=>setP(e.target.value)}/><input className="input" type="password" minLength="6" required placeholder="Confirm password" value={c} onChange={e=>setC(e.target.value)}/>{msg&&<p className="text-sm text-white/55">{msg}</p>}<button className="btn btn-orange"><Save size={16}/>Change Password</button></form></div>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<Admin/>}/></Routes>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);